### ISSUE TITLE
PolicyKit on Gnome

### ISSUE THREAD

**Issue by rmader** [Zer0CoolX/Fedora-KDE-Yubikey-U2F-2FA-Logins-Guide#1]
Hi there, thanks for this cool guide.

I'd like to note that for `/etc/pam.d/polkit-1` I had to add the `cue`. The comment below also suggests that it can only skipped for the login screen.

Note: this is on Gnome, not KDE, but I'd guess that things work similar for the polkit agent?

**Comment by Zer0CoolX** [comment]
Hello,

I mention that file here: https://github.com/Zer0CoolX/Fedora-KDE-Yubikey-U2F-2FA-Logins-Guide#policykit-kde-agent-2fa

As far as I am aware, KDE and more so SDDM (used for the login screen) do not support cue on login/GUI. Gnome may support it but is beyond the scope of this guide.

If this has changed for KDE/SDDM, I can update the guide but I am as of yet unaware of any such circumstance.

Thanks
